### PR TITLE
Add deepCloneState to getState()

### PR DESCRIPTION
**Pull request by Steve-RW**
This speeds up the setState method with large arrays

### CODE REVIEW

**Comment by DanWahlin** [comment]
Thanks Steve. I completely forgot about the private cloning going on which is obviously slowing things down for your scenario. Thanks for the PR (and subtle reminder :-)). Since this changes how things work internally I need to take a closer look. Now that 1000s are using it I have to be really careful about changes like this having any side effects. I'm tied up with a project deadline right now but as soon as I get a break I'll take a closer look into this. Thanks again.

**Comment by DanWahlin** [comment]
Thanks again @Steve-RW. I'm adding some additional tests for cloning vs not cloning and things seem to check out good so far. I'll let you know once I've done some more due diligence on it.

**Comment by Steve-RW** [comment]
Thanks @DanWahlin Really glad I could contribute.

**Comment by DanWahlin** [comment]
New version is out with the changes.

**Pull request merged**
